### ISSUE TITLE
This Is A Joke

### ISSUE THREAD

**Issue by ImmuneLion318** [jwix777ALT/decompiled-evon#1]
You Lied To Tarnish Evon's Fame I Hate The Owner And The Executor Itself It's Terrible, But Everything You Stated Was False And Misinformed Please Next Time Consider The Damage You Are Causing To Others And Stop Being So Egocentric And Selfish.

**Comment by thatkusari** [comment]
Now I believe the comments of this being a joke because the OP develops nihon (I think) and I use it

**Comment by ImmuneLion318** [comment]
I Do Make And Develop Nihon I Am The Original Owner/Founder Back In 2020, The Reddit Thread Was All False Information.

**Comment by madnessman666** [comment]
About browser hijacking: maybe i am wrong. I checked a webview2 installer and it touches same files that on screenshot. Ye here i wrong. I need to edit thread.

**Comment by madnessman666** [comment]
also krnl api in evon is broken.

**Comment by ImmuneLion318** [comment]
Eh Evon Like I Said Is By No Means A Great Executor But Just Blatantly Defaming It Wasn't Warranted With No General Information.

**Comment by madnessman666** [comment]
I edited a thread section 3. Ye in this section i wrong
